Added --directory option to rand

diff --git a/rand b/rand
--- a/rand
+++ b/rand
@@ -2,30 +2,38 @@
 
 N=1
 PATTERN=""
+DIR=""
 
 while [ $#  -gt 0 ] ; do
-	case $1 in 
-		-n|--num)
-			N=$2
-			shift
-			;;
-		-p|--pattern)
-			PATTERN="$2"
-			shift
-			;;
-		*)
-			echo "Invalid arg: $1"
-			exit 1
-			;;
-	esac
-	shift
+  case $1 in
+    -n|--num)
+      N=$2
+      shift
+      ;;
+    -p|--pattern)
+      PATTERN="$2"
+      shift
+      ;;
+    -d|--directory)
+      DIR="${DIR} $2"
+      shift
+      ;;
+    *)
+      echo "Invalid arg: $1"
+      exit 1
+      ;;
+  esac
+  shift
 done
 
+if [ -z "$DIR" ] ; then
+  DIR="."
+fi
 
 SHUF_ARGS="--head-count=${N}"
 
 if [ -n "$PATTERN" ] ; then
-	find . -type f -iname "$PATTERN" | shuf $SHUF_ARGS 
+  find $DIR \( -type l -o -type f \) -iname "$PATTERN" | shuf $SHUF_ARGS
 else
-	find . -type f | shuf $SHUF_ARGS 
+  find $DIR \( -type l -o -type f \) | shuf $SHUF_ARGS
 fi
